- name: Provision archlinux packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    # - name: Upgrade system
    #   pacman: update_cache=yes upgrade=yes

    - name: Install packages
      pacman:
        name:
          - gvim
          - git
          - emacs
          - wget
          - curl
          - fish
          - tmux
          - htop
          - nethogs
          - mosh
          - xmonad
          - xmonad-contrib
          - rsync
        state: latest

- name: Provision my configuration
  hosts: localhost
  connection: local
  become: yes
  become_user: gnzh
  environment:
    GOPATH: /home/gnzh/go-projects
  tasks:

    - name: Get dein script
      get_url: url=https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh dest=/tmp/dein.sh

    - name: Install dein
      command: "sh /tmp/dein.sh ~/.vim/bundle/dein.vim"

    - name: Install dotfiles
      git: accept_hostkey=true repo={{ item.url }} dest={{ item.dest }}
      with_items:
        - { url: 'https://github.com/syl20bnr/spacemacs',         dest: '~/.emacs.d'                  }
        - { url: 'https://github.com/sstephenson/rbenv.git',      dest: '~/.rbenv'                    }
        - { url: 'https://github.com/sstephenson/ruby-build.git', dest: '~/.rbenv/plugins/ruby-build' }
        - { url: 'git@github.com:Gonzih/.vim.git',                dest: '~/.vim'                      }
        - { url: 'git@github.com:Gonzih/.mc.git',                 dest: '~/.config/mc'                }
        - { url: 'git@github.com:Gonzih/.fish.git',               dest: '~/.config/fish'              }
        - { url: 'git@github.com:Gonzih/.xmonad.git',             dest: '~/.xmonad'                   }
        - { url: 'git@github.com:Gonzih/.mutt.git',               dest: '~/.mutt'                     }

    - name: Get go packages
      command: go get -u {{ item.url }}  creates=~/go-projects/bin/{{ item.bin }}
      with_items:
        - { url: 'github.com/nsf/gocode',            bin: 'gocode'    }
        - { url: 'golang.org/x/tools/cmd/goimports', bin: 'goimports' }
        - { url: 'github.com/golang/lint/golint',    bin: 'golint'    }
        - { url: 'github.com/kisielk/errcheck',      bin: 'errcheck'  }

    - name: Install glide for go
      command: bash -c 'curl https://glide.sh/get | sh' creates=~/go-projects/bin/glide

    - name: Symlink .vimrc
      file: src=~/.vim/vimrc dest={{ item }} state=link
      with_items:
        - ~/.vimrc
        - ~/.gvimrc

# vim:ft=ansible:
