- name: Provision my configuration
  hosts: localhost
  connection: local
  become: yes
  become_user: gnzh
  environment:
    GOPATH: /home/gnzh/go-projects

  vars:
    dotfiles:
      - { url: 'git@github.com:Gonzih/.vim.git',     dest: '~/.vim'            }
      - { url: 'git@github.com:Gonzih/.mc.git',      dest: '~/.config/mc'      }
      - { url: 'git@github.com:Gonzih/.fish.git',    dest: '~/.config/fish'    }
      - { url: 'git@github.com:Gonzih/.xmonad.git',  dest: '~/.xmonad'         }
      - { url: 'git@github.com:Gonzih/.mutt.git',    dest: '~/.mutt'           }
      - { url: 'git@github.com:Gonzih/nix-home.git', dest: '~/.config/nixpkgs' }
      - { url: 'https://github.com/oh-my-fish/plugin-foreign-env.git', dest: '~/.config/plugin-foreign-env' }

    ocamltools:
      - 'merlin'
      - 'ocp-indent'

    gotools:
      - 'github.com/stamblerre/gocode'
      - 'golang.org/x/tools/cmd/goimports'
      - 'golang.org/x/tools/cmd/godoc'
      - 'golang.org/x/lint/golint'
      - 'github.com/kisielk/errcheck'
      - 'github.com/ddollar/forego'
      - 'github.com/zmb3/gogetdoc'
      - 'github.com/Gonzih/simpleton'
      # - 'github.com/Gonzih/screensaver-off-go'
      # - 'github.com/Gonzih/external-screen-xps-helper'
      # - 'github.com/Gonzih/gocalendar-agenda-cli-tool'

  tasks:

    - name: Stash changes in dotfiles
      shell: test -d {{ item.dest }} && cd {{ item.dest }} && git stash || echo "No folder to stash"
      args:
        executable: /bin/sh
      with_items: "{{ dotfiles }}"

    - name: Install dotfiles
      git: accept_hostkey=true repo={{ item.url }} dest={{ item.dest }}
      with_items: "{{ dotfiles }}"

    - name: Pop changes in dotfiles
      shell: cd {{ item.dest }} && git stash pop
      ignore_errors: yes
      failed_when: no
      changed_when: yes
      with_items: "{{ dotfiles }}"

    # - name: Check if dein.vim exists
    #   stat:
    #     path: ~/.cache/dein.vim
    #   register: dein_stat

    # - name: Get dein script
    #   get_url: url=https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh dest=/tmp/dein.sh
    #   when: dein_stat.stat.exists == False

    # - name: Install dein
    #   command: sh /tmp/dein.sh ~/.cache/dein.vim
    #   when: dein_stat.stat.exists == False

    # - name: Get go packages
    #   command: go get -u {{ item }}
    #   with_items: "{{ gotools }}"

    # - name: Get ocaml tools
    #   command: opam install -y {{ item }}
    #   with_items: "{{ ocamltools }}"

    # - shell: which nvim
    #   register: which_nvim

    # - name: Symlink nvim
    #   file: src={{ which_nvim.stdout }} dest=~/bin/vim state=link

    # - name: Symlink nvim
    #   file: src=~/.config/nixpkgs/nix/lib/dotfiles/.tmux.conf dest=~/.tmux.conf state=link

#     - name: Setup rust
#       command: "{{ item }}"
#       with_items:
#         - rustup component add rust-src
#         - rustup component add rustfmt
#         - rustup component add clippy
#         - rustup component add rust-analysis
#         - rustup component add rls

# vim:ft=yaml.ansible:
