- name: Provision my configuration
  hosts: localhost
  connection: local
  become: yes
  become_user: gnzh
  environment:
    GOPATH: /home/gnzh/go-projects

  vars:
    dotfiles:
      - { url: 'https://github.com/syl20bnr/spacemacs',         dest: '~/.emacs.d'                  }
      - { url: 'https://github.com/sstephenson/rbenv.git',      dest: '~/.rbenv'                    }
      - { url: 'https://github.com/sstephenson/ruby-build.git', dest: '~/.rbenv/plugins/ruby-build' }
      - { url: 'git@github.com:Gonzih/.vim.git',                dest: '~/.vim'                      }
      - { url: 'git@github.com:Gonzih/.mc.git',                 dest: '~/.config/mc'                }
      - { url: 'git@github.com:Gonzih/.fish.git',               dest: '~/.config/fish'              }
      - { url: 'git@github.com:Gonzih/.xmonad.git',             dest: '~/.xmonad'                   }
      - { url: 'git@github.com:Gonzih/.mutt.git',               dest: '~/.mutt'                     }

  tasks:

    - name: Get dein script
      get_url: url=https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh dest=/tmp/dein.sh

    - name: Install dein
      command: sh /tmp/dein.sh ~/.vim/bundle/dein.vim creates=~/.vim/bundle/dein.vim

    - name: Stash changes in dotfiles
      shell: cd {{ item.dest }} && git stash
      with_items: "{{ dotfiles }}"

    - name: Install dotfiles
      git: accept_hostkey=true repo={{ item.url }} dest={{ item.dest }}
      with_items: "{{ dotfiles }}"

    - name: Pop changes in dotfiles
      shell: cd {{ item.dest }} && git stash pop
      ignore_errors: yes
      failed_when: no
      changed_when: yes
      with_items: "{{ dotfiles }}"

    - name: Get go packages
      command: go get -u {{ item }}
      with_items:
        - 'github.com/nsf/gocode'
        - 'golang.org/x/tools/cmd/goimports'
        - 'golang.org/x/tools/cmd/godoc'
        - 'github.com/golang/lint/golint'
        - 'github.com/kisielk/errcheck'
        - 'github.com/Gonzih/go-breathing'
        - 'github.com/asciimoo/wuzz'

    - name: Install glide for go
      shell: curl https://glide.sh/get | sh creates=~/go-projects/bin/glide

    - name: Symlink .vimrc
      file: src=~/.vim/vimrc dest={{ item }} state=link
      with_items:
        - ~/.vimrc
        - ~/.gvimrc

# vim:ft=ansible:
