- name: Provision archlinux on my new machine!
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: upgrade system
      pacman: update_cache=yes upgrade=yes

    - name: install packages
      pacman:
        name:
          - gvim
          - git
          - emacs
          - wget
          - curl
          - fish
          - tmux
          - xmonad
          - xmonad-contrib
          - xfce4
          - xfce4-goodies
          - go
          - firefox
          - thunderbird
        state: present

    - name: create gnzh user
      user:
        name: gnzh
        comment: "Max Gonzih"
        shell: /usr/bin/fish
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa.pub
        append: yes
        groups: gnzh,wheel,lock,video,audio,users
        update_password: on_create

- name: Provision my configuration on my new machine!
  hosts: localhost
  connection: local
  become: yes
  become_user: gnzh
  environment:
    GOPATH: /home/gnzh/go-projects
  tasks:

    - name: install spacemacs
      git: accept_hostkey=true accept_hostkey=true repo=https://github.com/syl20bnr/spacemacs dest=~/.emacs.d

    - name: install vimrc
      git: accept_hostkey=true accept_hostkey=true repo=git@github.com:Gonzih/.vim.git dest=~/.vim

    - name: install neobundle for vim
      git: accept_hostkey=true repo=https://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim

    - name: install mc config
      git: accept_hostkey=true force=true accept_hostkey=true repo=git@github.com:Gonzih/.mc.git dest=~/.config/mc

    - name: install fish config
      git: accept_hostkey=true accept_hostkey=true repo=git@github.com:Gonzih/.fish.git dest=~/.config/fish

    - name: install xmonad config
      git: accept_hostkey=true accept_hostkey=true repo=git@github.com:Gonzih/.xmonad.git dest=~/.xmonad

    - name: install mutt config
      git: accept_hostkey=true accept_hostkey=true repo=git@github.com:Gonzih/.mutt.git dest=~/.mutt

    - name: install rbenv
      git: accept_hostkey=true repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

    - name: install ruby-build
      git: accept_hostkey=true repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

    - name: go get gocode
      command: go get -u github.com/nsf/gocode creates=~/go-projects/bin/gocode

    - name: go get goimports
      command: go get -u golang.org/x/tools/cmd/goimports creates=~/go-projects/bin/goimports

    - name: go get golint
      command: go get -u github.com/golang/lint/golint creates=~/go-projects/bin/golint

    - name: go get errcheck
      command: go get -u github.com/kisielk/errcheck creates=~/go-projects/bin/errcheck

    - file: src=~/.vim/vimrc dest=~/.vimrc state=link
    - file: src=~/.vim/vimrc dest=~/.gvimrc state=link
